[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npx prisma migrate deploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[services.deploy]
startCommand = "npx serve@latest -s build -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.deploy.variables]
CI = "false"
REACT_APP_API_URL = "https://backend-production-1f5f.up.railway.app" 